import type Stripe from "stripe";

export const listProductsFixture = {
  object: "list" as const,
  data: [
    {
      id: "prod_RCeRR6vNdK8nUf",
      object: "product",
      active: true,
      attributes: [],
      created: 1731398852,
      default_price: "price_1QKF8KF7LKVFb0n5yWSyLylV",
      description:
        "If you really need to scale your data, this package is for you.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "50 sources" },
        { name: "1,000 collections" },
        { name: "1,000,000 items" },
        { name: "200 consumers" },
      ],
      metadata: {
        maxCollections: "1000",
        maxConsumers: "200",
        maxItems: "1000000",
        maxSources: "50",
      },
      name: "Enterprise",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731430069,
      url: null,
    } as Stripe.Product,
    {
      id: "prod_RCeKY8tFXtqv1U",
      object: "product",
      active: true,
      attributes: [],
      created: 1731398441,
      default_price: "price_1QKF1hF7LKVFb0n5KShVDTdL",
      description:
        "Perfect for businesses with multiple websites or content sources.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "5 sources" },
        { name: "50 collections" },
        { name: "100,000 items" },
        { name: "20 consumers" },
      ],
      metadata: {
        maxCollections: "50",
        maxConsumers: "20",
        maxItems: "100000",
        maxSources: "5",
        recommended: "true",
      },
      name: "Business",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731429945,
      url: null,
    } as Stripe.Product,
    {
      id: "prod_RCcC7Za6GSGKyG",
      object: "product",
      active: true,
      attributes: [],
      created: 1731390551,
      default_price: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
      description: "Perfect for single websites with one CMS.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "1 source" },
        { name: "10 collections" },
        { name: "1,000 items" },
        { name: "3 consumers" },
      ],
      metadata: {
        maxCollections: "10",
        maxConsumers: "3",
        maxItems: "1000",
        maxSources: "1",
      },
      name: "Starter",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731473703,
      url: null,
    } as Stripe.Product,
  ],
  has_more: false,
  url: "/v1/products",
} as Awaited<Stripe.ApiListPromise<Stripe.Product>>;

export const listLinksFixture = {
  object: "list",
  data: [
    {
      id: "plink_1QKLHPF7LKVFb0n5bTeLEDBv",
      object: "payment_link",
      active: true,
      after_completion: {
        hosted_confirmation: {
          custom_message: null,
        },
        type: "hosted_confirmation",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkmpOWzGmvrJJ",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 240000,
            amount_tax: 0,
            amount_total: 240000,
            currency: "eur",
            description: "Enterprise",
            price: {
              id: "price_1QKF8KF7LKVFb0n5yWSyLylV",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398852,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "enterprise_yearly",
              metadata: {},
              nickname: null,
              product: "prod_RCeRR6vNdK8nUf",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 240000,
              unit_amount_decimal: "240000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKLHPF7LKVFb0n5bTeLEDBv/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_8wM7uX2qv8Ui3Bu28d",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKL1FF7LKVFb0n50bET8QNe",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkWD9lGAcvkOD",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 24000,
            amount_tax: 0,
            amount_total: 24000,
            currency: "eur",
            description: "Enterprise",
            price: {
              id: "price_1QKFARF7LKVFb0n5Fhhzw1cu",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398983,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "enterprise_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCeRR6vNdK8nUf",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 24000,
              unit_amount_decimal: "24000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKL1FF7LKVFb0n50bET8QNe/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_bIYg1te9d0nM4FyeUY",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKxZF7LKVFb0n57zRVlMNa",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkStOjrUQehsj",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 24000,
            amount_tax: 0,
            amount_total: 24000,
            currency: "eur",
            description: "Business",
            price: {
              id: "price_1QKF1hF7LKVFb0n5KShVDTdL",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398441,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "business_yearly",
              metadata: {},
              nickname: null,
              product: "prod_RCeKY8tFXtqv1U",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 24000,
              unit_amount_decimal: "24000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKxZF7LKVFb0n57zRVlMNa/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_fZe7uX0in0nM3Bu4gj",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKuUF7LKVFb0n56XAherMh",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkPzc6nW2CSlZ",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 2400,
            amount_tax: 0,
            amount_total: 2400,
            currency: "eur",
            description: "Business",
            price: {
              id: "price_1QKF4XF7LKVFb0n5fjlAljqA",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398617,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "business_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCeKY8tFXtqv1U",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 2400,
              unit_amount_decimal: "2400",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKuUF7LKVFb0n56XAherMh/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_4gwbLd7KP1rQb3WdQS",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKllF7LKVFb0n55cGFsWUV",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "required",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkGD8E0UjQqV4",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 6000,
            amount_tax: 0,
            amount_total: 6000,
            currency: "eur",
            description: "Starter",
            price: {
              id: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398138,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "starter_yearly",
              metadata: {},
              nickname: "",
              product: "prod_RCcC7Za6GSGKyG",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 6000,
              unit_amount_decimal: "6000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKllF7LKVFb0n55cGFsWUV/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_dR68z19SX9Ym7RK4gh",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKFovF7LKVFb0n5DWBZOjUm",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "required",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCf98KQMLA6ttY",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 600,
            amount_tax: 0,
            amount_total: 600,
            currency: "eur",
            description: "Starter",
            price: {
              id: "price_1QKExxF7LKVFb0n56odwf4yi",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398209,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "starter_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCcC7Za6GSGKyG",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 600,
              unit_amount_decimal: "600",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKFovF7LKVFb0n5DWBZOjUm/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_4gw7uXghl8Ui7RKcMM",
    } as Stripe.PaymentLink,
  ],
  has_more: false,
  url: "/v1/payment_links",
} as Awaited<Stripe.ApiListPromise<Stripe.PaymentLink>>;
