import { Effect } from "effect";
import { Database } from "../../effect/services/Database";
import { DatabaseError } from "../../effect/errors";
import { sourceCollectionTable, influxTable } from "../../infra/db/schema";
import { and, eq } from "drizzle-orm";
import { pack, unpack } from "msgpackr";
import type { CollectionSchema, Filter } from "@contfu/svc-core";

export interface AddInfluxInput {
  /** Target collection ID */
  collectionId: number;
  /** Source ID */
  sourceId: number;
  /** External reference (Notion DB ID, Strapi content type, Web path) */
  ref: string;
  /** Display name for the source collection */
  name: string;
  /** If provided, use this existing source collection instead of creating one */
  existingSourceCollectionId?: number;
  /** Optional filters for the influx */
  filters?: Filter[];
  /** Optional schema (if known from probe results) */
  schema?: CollectionSchema;
  /** Whether refs may be transmitted for this influx. */
  includeRef?: boolean;
}

export interface AddInfluxResult {
  success: true;
  sourceCollectionId: number;
  influxId: number;
}

export interface AddInfluxError {
  success: false;
  error: string;
}

/**
 * Add an influx to a collection, auto-creating the SourceCollection if needed.
 * This is the main entry point for the "Add Influx" dialog.
 * IDs are auto-generated by the database.
 */
export const addInfluxWithSourceCollection = (userId: number, input: AddInfluxInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;

    let sourceCollectionId: number;

    if (input.existingSourceCollectionId) {
      // Verify the source collection exists and belongs to this user
      const [existing] = yield* Effect.tryPromise({
        try: () =>
          db
            .select({ id: sourceCollectionTable.id })
            .from(sourceCollectionTable)
            .where(
              and(
                eq(sourceCollectionTable.id, input.existingSourceCollectionId!),
                eq(sourceCollectionTable.userId, userId),
              ),
            )
            .limit(1),
        catch: (e) => new DatabaseError({ cause: e }),
      });

      if (!existing) {
        return { success: false as const, error: "Source collection not found" };
      }
      sourceCollectionId = existing.id;
    } else {
      // Create new source collection
      const [newSourceCollection] = yield* Effect.tryPromise({
        try: () =>
          db
            .insert(sourceCollectionTable)
            .values({
              userId,
              sourceId: input.sourceId,
              name: input.name,
              ref: Buffer.from(input.ref, "utf-8"),
              schema: input.schema ? pack(input.schema) : null,
            })
            .returning(),
        catch: (e) => new DatabaseError({ cause: e }),
      });

      sourceCollectionId = newSourceCollection.id;
    }

    // Check if influx already exists
    const [existingInflux] = yield* Effect.tryPromise({
      try: () =>
        db
          .select({ id: influxTable.id })
          .from(influxTable)
          .where(
            and(
              eq(influxTable.collectionId, input.collectionId),
              eq(influxTable.sourceCollectionId, sourceCollectionId),
            ),
          )
          .limit(1),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    if (existingInflux) {
      return {
        success: false as const,
        error: "This data source is already linked to this collection",
      };
    }

    // Get schema from source collection if not provided
    let schema = input.schema;
    if (!schema && input.existingSourceCollectionId) {
      const [sc] = yield* Effect.tryPromise({
        try: () =>
          db
            .select({ schema: sourceCollectionTable.schema })
            .from(sourceCollectionTable)
            .where(eq(sourceCollectionTable.id, sourceCollectionId))
            .limit(1),
        catch: (e) => new DatabaseError({ cause: e }),
      });

      if (sc?.schema) {
        schema = unpack(sc.schema) as CollectionSchema;
      }
    }

    // Create the influx
    const [influx] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(influxTable)
          .values({
            userId,
            collectionId: input.collectionId,
            sourceCollectionId,
            schema: schema ? pack(schema) : null,
            filters: input.filters?.length ? pack(input.filters) : null,
            includeRef: input.includeRef ?? true,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return {
      success: true as const,
      sourceCollectionId,
      influxId: influx.id,
    };
  }).pipe(Effect.withSpan("influxes.addWithSourceCollection", { attributes: { userId } }));
