import { Effect } from "effect";
import { Database } from "../../effect/services/Database";
import { DatabaseError } from "../../effect/errors";
import { collectionTable, influxTable, sourceCollectionTable } from "../../infra/db/schema";
import { and, eq } from "drizzle-orm";
import { pack, unpack } from "msgpackr";
import type { CollectionSchema, Filter } from "@contfu/svc-core";

export interface CreateInfluxInput {
  collectionId: number;
  sourceCollectionId: number;
  filters?: Filter[];
  schema?: CollectionSchema;
  includeRef?: boolean;
}

export interface InfluxResult {
  id: number;
  userId: number;
  collectionId: number;
  sourceCollectionId: number;
  schema: CollectionSchema | null;
  filters: Filter[] | null;
  includeRef: boolean;
  createdAt: Date;
  updatedAt: Date | null;
}

/**
 * Create an influx linking a source collection to a collection.
 * If schema is not provided, it will be fetched from the source collection.
 * The ID is auto-generated by the database.
 */
export const createInflux = (userId: number, input: CreateInfluxInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;

    const [collection, sourceCollection] = yield* Effect.tryPromise({
      try: () =>
        Promise.all([
          db
            .select({ id: collectionTable.id })
            .from(collectionTable)
            .where(
              and(eq(collectionTable.id, input.collectionId), eq(collectionTable.userId, userId)),
            )
            .limit(1),
          db
            .select({ id: sourceCollectionTable.id })
            .from(sourceCollectionTable)
            .where(
              and(
                eq(sourceCollectionTable.id, input.sourceCollectionId),
                eq(sourceCollectionTable.userId, userId),
              ),
            )
            .limit(1),
        ]),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    if (!collection[0]) {
      throw new Error("Collection not found");
    }
    if (!sourceCollection[0]) {
      throw new Error("Source collection not found");
    }

    // If no schema provided, fetch from source collection
    let schema = input.schema;
    if (!schema) {
      const [sc] = yield* Effect.tryPromise({
        try: () =>
          db
            .select({ schema: sourceCollectionTable.schema })
            .from(sourceCollectionTable)
            .where(
              and(
                eq(sourceCollectionTable.id, input.sourceCollectionId),
                eq(sourceCollectionTable.userId, userId),
              ),
            )
            .limit(1),
        catch: (e) => new DatabaseError({ cause: e }),
      });

      if (sc?.schema) {
        schema = unpack(sc.schema) as CollectionSchema;
      }
    }

    const [inserted] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(influxTable)
          .values({
            userId,
            collectionId: input.collectionId,
            sourceCollectionId: input.sourceCollectionId,
            schema: schema ? pack(schema) : null,
            filters: input.filters?.length ? pack(input.filters) : null,
            includeRef: input.includeRef ?? true,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return {
      id: inserted.id,
      userId: inserted.userId,
      collectionId: inserted.collectionId,
      sourceCollectionId: inserted.sourceCollectionId,
      schema: inserted.schema ? (unpack(inserted.schema) as CollectionSchema) : null,
      filters: inserted.filters ? (unpack(inserted.filters) as Filter[]) : null,
      includeRef: inserted.includeRef,
      createdAt: inserted.createdAt,
      updatedAt: inserted.updatedAt,
    } satisfies InfluxResult;
  }).pipe(Effect.withSpan("influxes.create", { attributes: { userId } }));
