// Generated by generate-js-migrations.ts. Do not edit manually.
import type { GeneratedMigration } from "./db-shared";

export const migrations: GeneratedMigration[] = [
  {
    name: "20260725101451_init",
    timestamp: 20260725101451,
    sql: `
CREATE TABLE "collections" (
	"name" text PRIMARY KEY,
	"displayName" text NOT NULL,
	"schema" blob NOT NULL,
	"i18n" blob
);
--> statement-breakpoint
CREATE TABLE "external_links" (
	"id" integer PRIMARY KEY,
	"from" integer NOT NULL,
	"url" text NOT NULL,
	CONSTRAINT "fk_external_links_from_items_id_fk" FOREIGN KEY ("from") REFERENCES "items"("id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "files" (
	"id" blob PRIMARY KEY,
	"status" integer NOT NULL,
	"mediaType" text NOT NULL,
	"meta" blob NOT NULL,
	"data" blob,
	"createdAt" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "internal_links" (
	"id" integer PRIMARY KEY,
	"prop" text,
	"from" integer NOT NULL,
	"to" integer NOT NULL,
	CONSTRAINT "fk_internal_links_from_items_id_fk" FOREIGN KEY ("from") REFERENCES "items"("id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "item_files" (
	"itemId" integer NOT NULL,
	"fileId" blob NOT NULL,
	CONSTRAINT "item_files_pk" PRIMARY KEY("itemId", "fileId"),
	CONSTRAINT "fk_item_files_itemId_items_id_fk" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE CASCADE,
	CONSTRAINT "fk_item_files_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "items" (
	"id" integer PRIMARY KEY,
	"collection" text NOT NULL,
	"props" blob,
	"locale" text,
	"content" blob,
	"changedAt" integer NOT NULL,
	"deletedAt" integer,
	CONSTRAINT "fk_items_collection_collections_name_fk" FOREIGN KEY ("collection") REFERENCES "collections"("name") ON UPDATE CASCADE
);
--> statement-breakpoint
CREATE TABLE "media_masters" (
	"fileId" blob PRIMARY KEY,
	"mediaType" text NOT NULL,
	"ext" text NOT NULL,
	"format" text NOT NULL,
	"configFingerprint" integer NOT NULL,
	"metadata" blob NOT NULL,
	"data" blob NOT NULL,
	"createdAt" integer NOT NULL,
	"updatedAt" integer NOT NULL,
	CONSTRAINT "fk_media_masters_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "media_variants" (
	"fileId" blob NOT NULL,
	"ext" text NOT NULL,
	"optsHash" integer NOT NULL,
	"opts" blob,
	"size" integer NOT NULL,
	"data" blob NOT NULL,
	"createdAt" integer NOT NULL,
	CONSTRAINT "media_variants_pk" PRIMARY KEY("fileId", "ext", "optsHash"),
	CONSTRAINT "fk_media_variants_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "sync" (
	"index" integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_external_links_from" ON "external_links" ("from");--> statement-breakpoint
CREATE INDEX "idx_internal_links_from" ON "internal_links" ("from","to");--> statement-breakpoint
CREATE INDEX "idx_internal_links_to" ON "internal_links" ("to");--> statement-breakpoint
CREATE INDEX "idx_items_collection" ON "items" ("collection");--> statement-breakpoint
CREATE INDEX "idx_items_locale" ON "items" ("locale");--> statement-breakpoint
CREATE INDEX "idx_items_changedAt" ON "items" ("changedAt");--> statement-breakpoint
CREATE INDEX "idx_items_deletedAt" ON "items" ("deletedAt");`,
  },
  {
    name: "20260813151309_singleton-sync",
    timestamp: 20260813151309,
    sql: `
PRAGMA foreign_keys=OFF;
--> statement-breakpoint
CREATE TABLE "__new_sync" (
	"key" integer PRIMARY KEY NOT NULL DEFAULT 1,
	"index" integer NOT NULL,
	CONSTRAINT "sync_singleton_key" CHECK("key" = 1)
);
--> statement-breakpoint
INSERT INTO "__new_sync"("key", "index")
SELECT 1, MAX("index") FROM "sync" HAVING COUNT(*) > 0;
--> statement-breakpoint
DROP TABLE "sync";
--> statement-breakpoint
ALTER TABLE "__new_sync" RENAME TO "sync";
--> statement-breakpoint
PRAGMA foreign_keys=ON;`,
  },
];
