#!/usr/bin/env bash
set -euo pipefail

# args: <oldsha> <newsha> <flag>
flag="${3:-0}"

# Only run on branch checkout / worktree creation
[ "$flag" = "1" ] || exit 0

pwt="$(git worktree list --porcelain | awk '$1=="worktree"{print $2; exit}')"
wt="$(git rev-parse --show-toplevel)"

# If the primary worktree is the same as the worktree, exit
[ "$pwt" = "$wt" ] && exit 0

cd $pwt
envs=$(find packages -name .env)
# nms="node_modules $(find packages -type d -name node_modules -prune -print)"

bun install
cd $wt
files=$envs
for file in $files; do ln -sf $pwt/$file $file; done
