#!/usr/bin/env bash
set -euo pipefail

# args: <oldsha> <newsha> <flag>
flag="${3:-0}"

# Only run on branch checkout / worktree creation
[ "$flag" = "1" ] || exit 0

primary_wt="$(git worktree list --porcelain \
  | awk '$1=="worktree"{print $2; exit}')"
# Worktree root
wt_root="$(git rev-parse --show-toplevel)"

cd $primary_wt
env_files=$(find packages -name .env)
cd $wt_root

for env_file in $env_files; do
  cp $primary_wt/$env_file $env_file
done

bun install
