{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contfu.fullname" . }}
  labels:
    {{- include "contfu.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  {{- if .Values.secrets.googleClientId }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientId }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientSecret }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.polarAccessToken }}
  POLAR_ACCESS_TOKEN: {{ .Values.secrets.polarAccessToken | quote }}
  {{- end }}
  {{- if .Values.secrets.polarWebhookSecret }}
  POLAR_WEBHOOK_SECRET: {{ .Values.secrets.polarWebhookSecret | quote }}
  {{- end }}
{{- end }}
