/**
 * @contfu/app - Full application wrapper
 */

export {
  // Database exports
  db,
  itemTable,
  itemLinkTable,
  assetTable,
  type DbItem,
  type NewItem,
  type ItemUpdate,
  type DbItemLink,
  type NewItemLink,
  type ItemLinkUpdate,
  type DbAsset,
  type NewAsset,
  type AssetUpdate,
  // Sync exports
  sync,
  // Item exports
  type ItemData,
  getItems,
  getItem,
  getLastChangedItem,
  createOrUpdateItem,
  createItem,
  updateItem,
  deleteItem,
  deleteItemsByIds,
  getItemIdsByCollection,
  getItemLinks,
  createItemLink,
  deleteOutgoingItemLinks,
  deleteItemLinksByRef,
  // Asset exports
  type Asset,
  type AssetData,
  type AssetReference,
  type AssetSyncProgress,
  type OnAssetProgress,
  createAsset,
  getAssetsByItem,
  deleteAssetsByItem,
  getAssetsByPage,
  deleteAssetsByPage,
  getOrphanAssets,
  deleteAssets,
  getAsset,
  getAssetByCanonical,
  // Connections exports
  type SyncOptions,
  type Source,
  type Connection,
  createConnection,
  // Media exports
  type MediaStore,
  // Hooks exports
  createEventHandler,
  composeHandlers,
  type EventHandler,
  type HookOptions,
  // Utility exports
  detectRuntime,
  deleteNulls,
  hashId,
  // Deprecated compatibility exports
  pageTable,
  pageLinkTable,
  type DbPage,
  type NewPage,
  type PageUpdate,
  type DbPageLink,
  type NewPageLink,
  type PageLinkUpdate,
  type PageData,
  getPages,
  getPage,
  getLastChangedPage,
  createOrUpdatePage,
  createPage,
  updatePage,
  deletePage,
  deletePagesByIds,
  getPageIdsByCollection,
  getPageLinks,
  createPageLink,
  deleteOutgoingPageLinks,
  deletePageLinksByRef,
} from "contfu";

export { connectPush } from "./core/connection";
