cache:
  paths:
    - node_modules/

stages:
  - check
  - publish
  - deploy

test:
  image: oven/bun:1.1.38-slim
  stage: check
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "main"
  script:
    - env
    - bun install
    - bun run test

dockerize-check:
  image: docker:27.3.1
  stage: check
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "main"
  services:
    - docker:27.3.1-dind
  variables:
    IMAGE_TAG_SYNC: $CI_REGISTRY_IMAGE:sync-$CI_COMMIT_REF_SLUG
    IMAGE_TAG_APP: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $IMAGE_TAG_SYNC --target sync .
    - docker build -t $IMAGE_TAG_APP --target app .

push:
  image: docker:27.3.1
  stage: publish
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main"
  services:
    - docker:27.3.1-dind
  variables:
    IMAGE_TAG_SYNC: $CI_REGISTRY_IMAGE:sync-$CI_COMMIT_REF_SLUG
    IMAGE_TAG_APP: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $IMAGE_TAG_SYNC --target sync .
    - docker push $IMAGE_TAG_SYNC
    - docker build -t $IMAGE_TAG_APP --target app .
    - docker push $IMAGE_TAG_APP
