import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";

const packageRoot = resolve(import.meta.dir, "..");
const migrationsDir = join(packageRoot, "db/migrations");
const outputFile = join(packageRoot, "src/infra/db/generated-migrations.ts");

async function readMigrationEntries() {
  const dirEntries = await readdir(migrationsDir, { withFileTypes: true });
  const migrations = await Promise.all(
    dirEntries
      .filter((entry) => entry.isDirectory())
      .map(async (entry) => {
        const name = entry.name;
        const sqlFile = join(migrationsDir, name, "migration.sql");
        const sql = await readFile(sqlFile, "utf8");
        const timestamp = Number.parseInt(name.slice(0, 14), 10);

        if (!Number.isFinite(timestamp)) {
          throw new Error(`Migration folder '${name}' does not start with a 14-digit timestamp`);
        }

        return { name, sql, timestamp };
      }),
  );

  return migrations.sort((a, b) => a.timestamp - b.timestamp || a.name.localeCompare(b.name));
}

function toTemplateLiteral(value: string): string {
  const normalized = value.replaceAll(/`([^`]+)`/g, '"$1"').replaceAll("${", "\\${");
  return `\`\n${normalized}\``;
}

function renderModule(migrations: Array<{ name: string; sql: string; timestamp: number }>): string {
  const body = migrations
    .map(
      (migration) =>
        `  { name: ${JSON.stringify(migration.name)}, timestamp: ${migration.timestamp}, sql: ${toTemplateLiteral(migration.sql)} },`,
    )
    .join("\n");

  return `// Generated by ${basename(import.meta.filename)}. Do not edit manually.\nimport type { GeneratedMigration } from "./db-shared";\n\nexport const migrations: GeneratedMigration[] = [\n${body}\n];\n`;
}

const migrations = await readMigrationEntries();
await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, renderModule(migrations));
console.log(`Wrote ${migrations.length} migrations to ${outputFile}`);
