import { db } from "../../infra/db/db";
import { consumerTable, type Consumer } from "../../infra/db/schema";
import type { BackendConsumer, CreateConsumerInput } from "../../domain/types";

function mapToBackendConsumer(consumer: Consumer): BackendConsumer {
  return {
    id: consumer.id,
    userId: consumer.userId,
    name: consumer.name,
    hasKey: consumer.key !== null,
    createdAt: consumer.createdAt,
  };
}

/**
 * Create a new consumer for a user.
 * The ID is auto-generated by the database.
 */
export async function createConsumer(
  userId: number,
  input: CreateConsumerInput,
): Promise<BackendConsumer> {
  const [inserted] = await db
    .insert(consumerTable)
    .values({
      userId,
      name: input.name,
      key: input.key ?? null,
    })
    .returning();

  return mapToBackendConsumer(inserted);
}
