import { Effect } from "effect";
import type { BackendConsumer, CreateConsumerInput } from "../../domain/types";
import { DatabaseError } from "../../effect/errors";
import { Database } from "../../effect/services/Database";
import { consumerTable, type Consumer } from "../../infra/db/schema";

function mapToBackendConsumer(consumer: Consumer): BackendConsumer {
  return {
    id: consumer.id,
    userId: consumer.userId,
    name: consumer.name,
    includeRef: consumer.includeRef,
    hasKey: consumer.key !== null,
    createdAt: consumer.createdAt,
  };
}

/**
 * Create a new consumer for a user.
 * The ID is auto-generated by the database.
 */
export const createConsumer = (userId: number, input: CreateConsumerInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;

    const [inserted] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(consumerTable)
          .values({
            userId,
            name: input.name,
            includeRef: input.includeRef ?? true,
            key: input.key ?? null,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return mapToBackendConsumer(inserted);
  }).pipe(Effect.withSpan("consumers.create", { attributes: { userId } }));
