import { db } from "../../infra/db/db";
import { sourceCollectionTable, type SourceCollection } from "../../infra/db/schema";

export interface CreateSourceCollectionInput {
  sourceId: number;
  name: string;
  ref?: Buffer | null;
  displayName?: string | null;
  schema?: Buffer | null;
}

/**
 * Create a new SourceCollection without auto-creating a Collection or Influx.
 * Use this when you want to create a SourceCollection and link it to an
 * existing Collection via an Influx yourself.
 * The ID is auto-generated by the database.
 */
export async function createSourceCollection(
  userId: number,
  input: CreateSourceCollectionInput,
): Promise<SourceCollection> {
  const [inserted] = await db
    .insert(sourceCollectionTable)
    .values({
      userId,
      sourceId: input.sourceId,
      name: input.name,
      displayName: input.displayName ?? null,
      ref: input.ref ?? null,
      schema: input.schema ?? null,
    })
    .returning();

  return inserted;
}
