import { db } from "../../infra/db/db";
import {
  sourceCollectionTable,
  collectionTable,
  influxTable,
  type SourceCollection,
} from "../../infra/db/schema";
import type { BackendCollection, CreateCollectionInput } from "../../domain/types";

function countItemIds(itemIds: Buffer | null): number {
  if (!itemIds) return 0;
  // Each item ID is 4 bytes
  return Math.floor(itemIds.length / 4);
}

function mapToBackendCollection(collection: SourceCollection): BackendCollection {
  return {
    id: collection.id,
    userId: collection.userId,
    sourceId: collection.sourceId,
    name: collection.name,
    hasRef: collection.ref !== null,
    refString: collection.ref ? collection.ref.toString("utf-8") : null,
    itemCount: countItemIds(collection.itemIds),
    createdAt: collection.createdAt,
    updatedAt: collection.updatedAt,
  };
}

/**
 * Create a new source collection for a user.
 * IDs are auto-generated by the database.
 *
 * TODO: Refactor to correct architecture where:
 * 1. Users create Collections (aggregation targets) first
 * 2. Source collections are discovered from source API (transient)
 * 3. Source collections are persisted only when linked to a Collection
 * Currently we auto-create a Collection when a SourceCollection is created (backwards).
 */
export async function createCollection(
  userId: number,
  input: CreateCollectionInput,
): Promise<BackendCollection> {
  // Use transaction to atomically create related records
  const inserted = await db.transaction(async (tx) => {
    // Create the source collection
    const [sourceCollection] = await tx
      .insert(sourceCollectionTable)
      .values({
        userId,
        sourceId: input.sourceId,
        name: input.name,
        ref: input.ref ?? null,
        itemIds: input.itemIds ?? null,
      })
      .returning();

    // Create a corresponding collection (aggregation target)
    const [collection] = await tx
      .insert(collectionTable)
      .values({
        userId,
        name: input.name,
      })
      .returning();

    // Create influx from source collection to collection (no filters)
    await tx.insert(influxTable).values({
      userId,
      collectionId: collection.id,
      sourceCollectionId: sourceCollection.id,
      schema: null,
      filters: null,
    });

    return sourceCollection;
  });

  return mapToBackendCollection(inserted);
}
