// Re-export everything from @contfu/svc-core so external integrations
// only need to depend on @contfu/svc-api.
export {
  // API types
  ApiError,
  type ApiStatus,
  type ApiWorkspace,
  type ApiOrganization,
  type ApiOrganizationUsage,
  type ApiOrganizationMember,
  type ApiWorkspaceMember,
  type ApiIntegration,
  type ApiTargetFailedDelivery,
  type ApiSourceOperation,
  type PauseSourceSyncResult,
  type ResumeSourceSyncResult,
  type FullResyncResult,
  type ApiIncident,
  type ListIncidentsInput,
  type DismissIncidentResult,
  type CreateIntegrationBody,
  type UpdateIntegrationBody,
  type CreateCollectionBody,
  type UpdateCollectionBody,
  type CreateFlowBody,
  type UpdateFlowBody,
  // Domain types
  type ServiceCollection,
  type ServiceFlow,
  type ServiceFlowWithDetails,
  type Filter,
  type MappingRule,
  type CollectionSchema,
  type GeoPoint,
  type SchemaValue,
  type RefTargets,
  type TypeGenerationInput,
  type Color,
  type ColorRgba,
  type CollectionI18nConfig,
  type IntegrationI18nConfig,
  type EffectiveCollectionI18nConfig,
  type ScannedCollection,
  type AddedScannedCollection,
  type AddScannedCollectionsBody,
  type AddScannedCollectionsResult,
  type CreateWorkspaceBody,
  type UpdateWorkspaceBody,
  type CreateOrganizationBody,
  type UpdateOrganizationBody,
  type CreateOrganizationInvitationBody,
  type CreateOrganizationInvitationResult,
  type CreateWorkspaceInvitationBody,
  type CreateWorkspaceInvitationResult,
  // Constants & utilities
  SourceOperationType,
  SourceOperationStatus,
  IncidentResolutionMode,
  IncidentType,
  IncidentTypeName,
  getIncidentPresentation,
  IntegrationType,
  IntegrationTypeMeta,
  WebAuthType,
  PropertyType,
  propertyTypeBase,
  asColor,
  colorFromHex,
  colorFromRgba,
  colorToCss,
  colorToHex,
  colorToRgba,
  isColor,
  schemaType,
  schemaEnumValues,
  mergeSchemaValues,
  generateTypeScript,
  generateApplicationIntegrationTypes,
  generateConsumerTypes,
  FilterOperator,
  BCP47_LOCALES,
  canonicalizeBcp47,
  isBcp47,
} from "@contfu/svc-core";
