export const PropertyType = {
  NULL: 0,
  STRING: 2,
  STRINGS: 4,
  NUMBER: 8,
  NUMBERS: 16,
  BOOLEAN: 32,
  REF: 64,
  REFS: 128,
  FILE: 256,
  FILES: 512,
  DATE: 1024,
  ENUM: 2048,
  ENUMS: 4096,
} as const;
export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType];

export type SchemaValue = number | [number, string[]];
export type CollectionSchema = Record<string, SchemaValue>;

/** Extract the numeric type from a schema value (tuple or plain number). */
export function schemaType(v: SchemaValue): number {
  return Array.isArray(v) ? v[0] : v;
}

/** Extract enum values from a schema value, or undefined if not an enum tuple. */
export function schemaEnumValues(v: SchemaValue): string[] | undefined {
  return Array.isArray(v) ? v[1] : undefined;
}

/**
 * Merge two schema values for the same property (e.g. from multiple inflows).
 * Bitwise-ORs the types; unions the enum values if either side has them.
 */
export function mergeSchemaValues(a: SchemaValue, b: SchemaValue): SchemaValue {
  const merged = schemaType(a) | schemaType(b);
  const valsA = schemaEnumValues(a);
  const valsB = schemaEnumValues(b);
  if (valsA || valsB) {
    const combined = [...new Set([...(valsA ?? []), ...(valsB ?? [])])];
    return [merged, combined];
  }
  return merged;
}

export type RefTargets = Record<string, string[]>;

function toInterfaceName(name: string): string {
  return name[0].toUpperCase() + name.slice(1);
}

type RefFormat = "interface" | "lookup";

function formatRefTargets(targets: string[], format: RefFormat): string {
  if (format === "lookup") {
    return targets.map((t) => `ContfuCollections["${t}"]`).join(" | ");
  }
  return targets.map(toInterfaceName).join(" | ");
}

function propertyTypeToTs(
  type: number,
  targets?: string[],
  refFormat: RefFormat = "interface",
  enumValues?: string[],
): string {
  switch (type) {
    case PropertyType.STRING:
      return "string";
    case PropertyType.STRINGS:
      return "string[]";
    case PropertyType.NUMBER:
      return "number";
    case PropertyType.NUMBERS:
      return "number[]";
    case PropertyType.BOOLEAN:
      return "boolean";
    case PropertyType.REF:
      if (targets && targets.length > 0) {
        return formatRefTargets(targets, refFormat);
      }
      return "string";
    case PropertyType.REFS:
      if (targets && targets.length > 0) {
        const union = formatRefTargets(targets, refFormat);
        return targets.length > 1 ? `(${union})[]` : `${union}[]`;
      }
      return "string[]";
    case PropertyType.FILE:
      return "{ url: string; alt?: string }";
    case PropertyType.FILES:
      return "{ url: string; alt?: string }[]";
    case PropertyType.DATE:
      return "string";
    case PropertyType.ENUM:
      if (enumValues && enumValues.length > 0) {
        return enumValues.map((v) => JSON.stringify(v)).join(" | ");
      }
      return "string";
    case PropertyType.ENUMS:
      if (enumValues && enumValues.length > 0) {
        const union = enumValues.map((v) => JSON.stringify(v)).join(" | ");
        return enumValues.length > 1 ? `(${union})[]` : `${union}[]`;
      }
      return "string[]";
    default:
      return "unknown";
  }
}

export interface TypeGenerationInput {
  name: string;
  displayName: string;
  schema: CollectionSchema;
  refTargets?: RefTargets;
  inflowSchemas?: CollectionSchema[];
}

/**
 * Render one union member as a block of lines with the given base indent.
 * baseIndent is the indent for the leading `|` character.
 * Properties are indented 4 spaces further; closing `}` 2 spaces further.
 */
function renderUnionMember(
  schema: CollectionSchema,
  refTargets: RefTargets | undefined,
  refFormat: RefFormat,
  baseIndent: string,
  isLast: boolean,
): string[] {
  const lines: string[] = [`${baseIndent}| {`];
  for (const [key, value] of Object.entries(schema)) {
    lines.push(
      `${baseIndent}    ${key}: ${propertyTypeToTs(schemaType(value), refTargets?.[key], refFormat, schemaEnumValues(value))};`,
    );
  }
  lines.push(`${baseIndent}  }${isLast ? ";" : ""}`);
  return lines;
}

function deduplicateSchemas(schemas: CollectionSchema[]): CollectionSchema[] {
  const seen = new Set<string>();
  return schemas.filter((schema) => {
    const key = JSON.stringify(Object.entries(schema).sort(([a], [b]) => a.localeCompare(b)));
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function generateTypeScript(collections: TypeGenerationInput[]): string {
  const lines: string[] = ["// Auto-generated by Contfu — do not edit", ""];

  for (const col of collections) {
    const interfaceName = toInterfaceName(col.name);
    lines.push(`/** ${col.displayName} */`);

    const unique = col.inflowSchemas ? deduplicateSchemas(col.inflowSchemas) : [];
    if (unique.length >= 2) {
      lines.push(`export type ${interfaceName} =`);
      for (let i = 0; i < unique.length; i++) {
        lines.push(
          ...renderUnionMember(
            unique[i],
            col.refTargets,
            "interface",
            "  ",
            i === unique.length - 1,
          ),
        );
      }
    } else {
      lines.push(`export interface ${interfaceName} {`);
      for (const [key, value] of Object.entries(col.schema)) {
        lines.push(
          `  ${key}: ${propertyTypeToTs(schemaType(value), col.refTargets?.[key], "interface", schemaEnumValues(value))};`,
        );
      }
      lines.push("}");
    }

    lines.push("");
  }

  return lines.join("\n");
}

export function generateConsumerTypes(collections: TypeGenerationInput[]): string {
  const lines: string[] = ["// Auto-generated by Contfu — do not edit", ""];

  lines.push("export type ContfuCollections = {");

  for (const col of collections) {
    lines.push(`  /** ${col.displayName} */`);

    const unique = col.inflowSchemas ? deduplicateSchemas(col.inflowSchemas) : [];
    if (unique.length >= 2) {
      lines.push(`  ${col.name}:`);
      for (let i = 0; i < unique.length; i++) {
        lines.push(
          ...renderUnionMember(
            unique[i],
            col.refTargets,
            "lookup",
            "    ",
            i === unique.length - 1,
          ),
        );
      }
    } else {
      lines.push(`  ${col.name}: {`);
      for (const [key, value] of Object.entries(col.schema)) {
        lines.push(
          `    ${key}: ${propertyTypeToTs(schemaType(value), col.refTargets?.[key], "lookup", schemaEnumValues(value))};`,
        );
      }
      lines.push(`  };`);
    }
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}
