export const PropertyType = {
  NULL: 0,
  STRING: 2,
  STRINGS: 4,
  NUMBER: 8,
  NUMBERS: 16,
  BOOLEAN: 32,
  REF: 64,
  REFS: 128,
  FILE: 256,
  FILES: 512,
  DATE: 1024,
} as const;
export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType];

export type CollectionSchema = Record<string, number>;

function propertyTypeToTs(type: number): string {
  switch (type) {
    case PropertyType.STRING:
      return "string";
    case PropertyType.STRINGS:
      return "string[]";
    case PropertyType.NUMBER:
      return "number";
    case PropertyType.NUMBERS:
      return "number[]";
    case PropertyType.BOOLEAN:
      return "boolean";
    case PropertyType.REF:
      return "string";
    case PropertyType.REFS:
      return "string[]";
    case PropertyType.FILE:
      return "{ url: string; alt?: string }";
    case PropertyType.FILES:
      return "{ url: string; alt?: string }[]";
    case PropertyType.DATE:
      return "string";
    default:
      return "unknown";
  }
}

export interface TypeGenerationInput {
  name: string;
  displayName: string;
  schema: CollectionSchema;
}

export function generateTypeScript(collections: TypeGenerationInput[]): string {
  const lines: string[] = ["// Auto-generated by Contfu — do not edit", ""];

  for (const col of collections) {
    const interfaceName = col.name[0].toUpperCase() + col.name.slice(1);
    lines.push(`/** ${col.displayName} */`);
    lines.push(`export interface ${interfaceName} {`);

    for (const [key, type] of Object.entries(col.schema)) {
      lines.push(`  ${key}: ${propertyTypeToTs(type)};`);
    }

    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

export function generateConsumerTypes(collections: TypeGenerationInput[]): string {
  const lines: string[] = ["// Auto-generated by Contfu — do not edit", ""];

  lines.push("export type ContfuCollections = {");

  for (const col of collections) {
    lines.push(`  /** ${col.displayName} */`);
    lines.push(`  ${col.name}: {`);

    for (const [key, type] of Object.entries(col.schema)) {
      lines.push(`    ${key}: ${propertyTypeToTs(type)};`);
    }

    lines.push(`  };`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}
