import type Stripe from "stripe";

export const listProductsFixture = {
  object: "list" as const,
  data: [
    {
      id: "prod_RCeRR6vNdK8nUf",
      object: "product",
      active: true,
      attributes: [],
      created: 1731398852,
      default_price: "price_1QKF8KF7LKVFb0n5yWSyLylV",
      description:
        "If you really need to scale your data, this package is for you.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "50 sources" },
        { name: "1,000 collections" },
        { name: "1,000,000 items" },
        { name: "200 consumers" },
      ],
      metadata: {
        maxCollections: "1000",
        maxConsumers: "200",
        maxItems: "1000000",
        maxSources: "50",
      },
      name: "Enterprise",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731430069,
      url: null,
    } as Stripe.Product,
    {
      id: "prod_RCeKY8tFXtqv1U",
      object: "product",
      active: true,
      attributes: [],
      created: 1731398441,
      default_price: "price_1QKF1hF7LKVFb0n5KShVDTdL",
      description:
        "Perfect for businesses with multiple websites or content sources.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "5 sources" },
        { name: "50 collections" },
        { name: "100,000 items" },
        { name: "20 consumers" },
      ],
      metadata: {
        maxCollections: "50",
        maxConsumers: "20",
        maxItems: "100000",
        maxSources: "5",
        recommended: "true",
      },
      name: "Business",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731429945,
      url: null,
    } as Stripe.Product,
    {
      id: "prod_RCcC7Za6GSGKyG",
      object: "product",
      active: true,
      attributes: [],
      created: 1731390551,
      default_price: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
      description: "Perfect for single websites with one CMS.",
      images: [],
      livemode: false,
      marketing_features: [
        { name: "1 source" },
        { name: "10 collections" },
        { name: "1,000 items" },
        { name: "3 consumers" },
      ],
      metadata: {
        maxCollections: "10",
        maxConsumers: "3",
        maxItems: "1000",
        maxSources: "1",
      },
      name: "Starter",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_10000000",
      type: "service",
      unit_label: null,
      updated: 1731473703,
      url: null,
    } as Stripe.Product,
  ],
  has_more: false,
  url: "/v1/products",
} as Awaited<Stripe.ApiListPromise<Stripe.Product>>;

export const listLinksFixture = {
  object: "list",
  data: [
    {
      id: "plink_1QKLHPF7LKVFb0n5bTeLEDBv",
      object: "payment_link",
      active: true,
      after_completion: {
        hosted_confirmation: {
          custom_message: null,
        },
        type: "hosted_confirmation",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkmpOWzGmvrJJ",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 240000,
            amount_tax: 0,
            amount_total: 240000,
            currency: "eur",
            description: "Enterprise",
            price: {
              id: "price_1QKF8KF7LKVFb0n5yWSyLylV",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398852,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "enterprise_yearly",
              metadata: {},
              nickname: null,
              product: "prod_RCeRR6vNdK8nUf",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 240000,
              unit_amount_decimal: "240000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKLHPF7LKVFb0n5bTeLEDBv/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_8wM7uX2qv8Ui3Bu28d",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKL1FF7LKVFb0n50bET8QNe",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkWD9lGAcvkOD",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 24000,
            amount_tax: 0,
            amount_total: 24000,
            currency: "eur",
            description: "Enterprise",
            price: {
              id: "price_1QKFARF7LKVFb0n5Fhhzw1cu",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398983,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "enterprise_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCeRR6vNdK8nUf",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 24000,
              unit_amount_decimal: "24000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKL1FF7LKVFb0n50bET8QNe/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_bIYg1te9d0nM4FyeUY",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKxZF7LKVFb0n57zRVlMNa",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkStOjrUQehsj",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 24000,
            amount_tax: 0,
            amount_total: 24000,
            currency: "eur",
            description: "Business",
            price: {
              id: "price_1QKF1hF7LKVFb0n5KShVDTdL",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398441,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "business_yearly",
              metadata: {},
              nickname: null,
              product: "prod_RCeKY8tFXtqv1U",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 24000,
              unit_amount_decimal: "24000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKxZF7LKVFb0n57zRVlMNa/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_fZe7uX0in0nM3Bu4gj",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKuUF7LKVFb0n56XAherMh",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "auto",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkPzc6nW2CSlZ",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 2400,
            amount_tax: 0,
            amount_total: 2400,
            currency: "eur",
            description: "Business",
            price: {
              id: "price_1QKF4XF7LKVFb0n5fjlAljqA",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398617,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "business_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCeKY8tFXtqv1U",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 2400,
              unit_amount_decimal: "2400",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKuUF7LKVFb0n56XAherMh/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_4gwbLd7KP1rQb3WdQS",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKKllF7LKVFb0n55cGFsWUV",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "required",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCkGD8E0UjQqV4",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 6000,
            amount_tax: 0,
            amount_total: 6000,
            currency: "eur",
            description: "Starter",
            price: {
              id: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398138,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "starter_yearly",
              metadata: {},
              nickname: "",
              product: "prod_RCcC7Za6GSGKyG",
              recurring: {
                aggregate_usage: null,
                interval: "year",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 6000,
              unit_amount_decimal: "6000",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKKllF7LKVFb0n55cGFsWUV/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_dR68z19SX9Ym7RK4gh",
    } as Stripe.PaymentLink,
    {
      id: "plink_1QKFovF7LKVFb0n5DWBZOjUm",
      object: "payment_link",
      active: true,
      after_completion: {
        redirect: {
          url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
        },
        type: "redirect",
      },
      allow_promotion_codes: false,
      application: null,
      application_fee_amount: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: true,
        liability: {
          type: "self",
        },
      },
      billing_address_collection: "required",
      consent_collection: {
        payment_method_reuse_agreement: null,
        promotions: "none",
        terms_of_service: "none",
      },
      currency: "eur",
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer_creation: "if_required",
      inactive_message: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      line_items: {
        object: "list",
        data: [
          {
            id: "li_RCf98KQMLA6ttY",
            object: "item",
            amount_discount: 0,
            amount_subtotal: 600,
            amount_tax: 0,
            amount_total: 600,
            currency: "eur",
            description: "Starter",
            price: {
              id: "price_1QKExxF7LKVFb0n56odwf4yi",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1731398209,
              currency: "eur",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: "starter_monthly",
              metadata: {},
              nickname: null,
              product: "prod_RCcC7Za6GSGKyG",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 600,
              unit_amount_decimal: "600",
            },
            quantity: 1,
          },
        ],
        has_more: false,
        url: "/v1/payment_links/plink_1QKFovF7LKVFb0n5DWBZOjUm/line_items",
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      payment_intent_data: null,
      payment_method_collection: "always",
      payment_method_types: null,
      phone_number_collection: {
        enabled: false,
      },
      restrictions: null,
      shipping_address_collection: null,
      shipping_options: [],
      submit_type: "auto",
      subscription_data: {
        description: null,
        invoice_settings: {
          issuer: {
            type: "self",
          },
        },
        metadata: {},
        trial_period_days: 7,
        trial_settings: {
          end_behavior: {
            missing_payment_method: "pause",
          },
        },
      },
      tax_id_collection: {
        enabled: true,
        required: "never",
      },
      transfer_data: null,
      url: "https://buy.stripe.com/test_4gw7uXghl8Ui7RKcMM",
    } as Stripe.PaymentLink,
  ],
  has_more: false,
  url: "/v1/payment_links",
} as Awaited<Stripe.ApiListPromise<Stripe.PaymentLink>>;

export const checkoutSessionFixture = {
  id: "cs_test_a1MvPmu5lzlTAcGYTQppEkiC1v6gRnmmrHaHJm0s3pgXFewdjEInpJuGlU",
  object: "checkout.session",
  adaptive_pricing: null,
  after_expiration: null,
  allow_promotion_codes: false,
  amount_subtotal: 0,
  amount_total: 0,
  automatic_tax: {
    enabled: true,
    liability: {
      type: "self",
    },
    status: "complete",
  },
  billing_address_collection: "required",
  cancel_url: "https://stripe.com",
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: {
    payment_method_reuse_agreement: null,
    promotions: "none",
    terms_of_service: "none",
  },
  created: 1731561333,
  currency: "eur",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: "cus_RDM9AYJNf43reP",
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: "City",
      country: "DE",
      line1: "XY",
      line2: null,
      postal_code: "11111",
      state: null,
    },
    email: "test@test.com",
    name: "Test",
    phone: null,
    tax_exempt: "none",
    tax_ids: [
      {
        type: "eu_vat",
        value: "DE123456789",
      },
    ],
  },
  customer_email: null,
  expires_at: 1731647732,
  invoice: "in_1QKvR0F7LKVFb0n5odKx14ZB",
  invoice_creation: null,
  livemode: false,
  locale: "auto",
  metadata: {},
  mode: "subscription",
  payment_intent: null,
  payment_link: "plink_1QKKllF7LKVFb0n55cGFsWUV",
  payment_method_collection: "always",
  payment_method_configuration_details: {
    id: "pmc_1QKHE9F7LKVFb0n5Mwnd6Ced",
    parent: null,
  },
  payment_method_options: {
    card: {
      request_three_d_secure: "automatic",
    },
  },
  payment_method_types: ["card", "link", "paypal"],
  payment_status: "paid",
  phone_number_collection: {
    enabled: false,
  },
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: ["always"],
    payment_method_remove: null,
    payment_method_save: null,
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: "complete",
  submit_type: "auto",
  subscription: "sub_1QKvR0F7LKVFb0n5dQmieAKs",
  success_url: "https://localhost:5173/register?id={CHECKOUT_SESSION_ID}",
  tax_id_collection: {
    enabled: true,
    required: "never",
  },
  total_details: {
    amount_discount: 0,
    amount_shipping: 0,
    amount_tax: 0,
  },
  ui_mode: "hosted",
  url: null,
} as Stripe.Checkout.Session;

export const subscriptionRetrieveFixture = {
  id: "sub_1QKvR0F7LKVFb0n5dQmieAKs",
  object: "subscription",
  application: null,
  application_fee_percent: null,
  automatic_tax: {
    enabled: true,
    liability: {
      type: "self",
    },
  },
  billing_cycle_anchor: 1732166257,
  billing_cycle_anchor_config: null,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: {
    comment: null,
    feedback: null,
    reason: null,
  },
  collection_method: "charge_automatically",
  created: 1731561457,
  currency: "eur",
  current_period_end: 1732166257,
  current_period_start: 1731561457,
  customer: "cus_RDM9AYJNf43reP",
  days_until_due: null,
  default_payment_method: "pm_1QKvQrF7LKVFb0n5haIyPTpb",
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  ended_at: null,
  invoice_settings: {
    account_tax_ids: null,
    issuer: {
      type: "self",
    },
  },
  items: {
    object: "list",
    data: [
      {
        id: "si_RDM9MWZO3ACrRo",
        object: "subscription_item",
        billing_thresholds: null,
        created: 1731561458,
        discounts: [],
        metadata: {},
        plan: {
          id: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
          object: "plan",
          active: true,
          aggregate_usage: null,
          amount: 6000,
          amount_decimal: "6000",
          billing_scheme: "per_unit",
          created: 1731398138,
          currency: "eur",
          interval: "year",
          interval_count: 1,
          livemode: false,
          metadata: {},
          meter: null,
          nickname: "",
          product: "prod_RCcC7Za6GSGKyG",
          tiers_mode: null,
          transform_usage: null,
          trial_period_days: null,
          usage_type: "licensed",
        },
        price: {
          id: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
          object: "price",
          active: true,
          billing_scheme: "per_unit",
          created: 1731398138,
          currency: "eur",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: "starter_yearly",
          metadata: {},
          nickname: "",
          product: "prod_RCcC7Za6GSGKyG",
          recurring: {
            aggregate_usage: null,
            interval: "year",
            interval_count: 1,
            meter: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          tax_behavior: "exclusive",
          tiers_mode: null,
          transform_quantity: null,
          type: "recurring",
          unit_amount: 6000,
          unit_amount_decimal: "6000",
        },
        quantity: 1,
        subscription: "sub_1QKvR0F7LKVFb0n5dQmieAKs",
        tax_rates: [],
      },
    ],
    has_more: false,
    total_count: 1,
    url: "/v1/subscription_items?subscription=sub_1QKvR0F7LKVFb0n5dQmieAKs",
  },
  latest_invoice: "in_1QKvR0F7LKVFb0n5odKx14ZB",
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: {
        network: null,
        request_three_d_secure: "automatic",
      },
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
    save_default_payment_method: "off",
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: "price_1QKEwoF7LKVFb0n5IIcF1jVx",
    object: "plan",
    active: true,
    aggregate_usage: null,
    amount: 6000,
    amount_decimal: "6000",
    billing_scheme: "per_unit",
    created: 1731398138,
    currency: "eur",
    interval: "year",
    interval_count: 1,
    livemode: false,
    metadata: {},
    meter: null,
    nickname: "",
    product: "prod_RCcC7Za6GSGKyG",
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: "licensed",
  },
  quantity: 1,
  schedule: null,
  start_date: 1731561457,
  status: "trialing",
  test_clock: null,
  transfer_data: null,
  trial_end: 1732166257,
  trial_settings: {
    end_behavior: {
      missing_payment_method: "create_invoice",
    },
  },
  trial_start: 1731561457,
} as Stripe.Subscription;
