import { Effect } from "effect";
import { and, eq } from "drizzle-orm";
import { pack, unpack } from "msgpackr";
import { IncidentType, type SchemaIncompatibleDetails } from "@contfu/svc-core";
import { Database } from "../../effect/services/Database";
import { DatabaseError } from "../../effect/errors";
import { incidentTable, influxTable } from "../../infra/db/schema";

export interface CreateIncidentInput {
  influxId: number;
  type: IncidentType;
  message: string;
  details?: SchemaIncompatibleDetails | Record<string, unknown>;
}

export interface IncidentResult {
  id: number;
  userId: number;
  influxId: number;
  type: IncidentType;
  message: string;
  details: Record<string, unknown> | null;
  resolved: boolean;
  createdAt: Date;
  resolvedAt: Date | null;
}

/**
 * Create a new incident for an influx.
 * The ID is auto-generated by the database.
 */
export const createIncident = (userId: number, input: CreateIncidentInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;

    const [influx] = yield* Effect.tryPromise({
      try: () =>
        db
          .select({ id: influxTable.id })
          .from(influxTable)
          .where(and(eq(influxTable.id, input.influxId), eq(influxTable.userId, userId)))
          .limit(1),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    if (!influx) {
      throw new Error("Influx not found");
    }

    const [inserted] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(incidentTable)
          .values({
            userId,
            influxId: input.influxId,
            type: input.type,
            message: input.message,
            details: input.details ? pack(input.details) : null,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return {
      id: inserted.id,
      userId: inserted.userId,
      influxId: inserted.influxId,
      type: Number(inserted.type) as IncidentType,
      message: inserted.message,
      details: inserted.details ? (unpack(inserted.details) as Record<string, unknown>) : null,
      resolved: inserted.resolved,
      createdAt: inserted.createdAt,
      resolvedAt: inserted.resolvedAt,
    } satisfies IncidentResult;
  }).pipe(
    Effect.withSpan("incidents.create", { attributes: { userId, influxId: input.influxId } }),
  );
