import { db } from "../../infra/db/db";
import { incidentTable, influxTable } from "../../infra/db/schema";
import { pack, unpack } from "msgpackr";
import { IncidentType, type SchemaIncompatibleDetails } from "@contfu/svc-core";
import { and, eq } from "drizzle-orm";

export interface CreateIncidentInput {
  influxId: number;
  type: IncidentType;
  message: string;
  details?: SchemaIncompatibleDetails | Record<string, unknown>;
}

export interface IncidentResult {
  id: number;
  userId: number;
  influxId: number;
  type: IncidentType;
  message: string;
  details: Record<string, unknown> | null;
  resolved: boolean;
  createdAt: Date;
  resolvedAt: Date | null;
}

/**
 * Create a new incident for an influx.
 * The ID is auto-generated by the database.
 */
export async function createIncident(
  userId: number,
  input: CreateIncidentInput,
): Promise<IncidentResult> {
  const [influx] = await db
    .select({ id: influxTable.id })
    .from(influxTable)
    .where(and(eq(influxTable.id, input.influxId), eq(influxTable.userId, userId)))
    .limit(1);

  if (!influx) {
    throw new Error("Influx not found");
  }

  const [inserted] = await db
    .insert(incidentTable)
    .values({
      userId,
      influxId: input.influxId,
      type: input.type,
      message: input.message,
      details: input.details ? pack(input.details) : null,
    })
    .returning();

  return {
    id: inserted.id,
    userId: inserted.userId,
    influxId: inserted.influxId,
    type: Number(inserted.type) as IncidentType,
    message: inserted.message,
    details: inserted.details ? (unpack(inserted.details) as Record<string, unknown>) : null,
    resolved: inserted.resolved,
    createdAt: inserted.createdAt,
    resolvedAt: inserted.resolvedAt,
  };
}
