apiVersion: v2
name: contfu
description: A Helm chart for Contfu proxy CMS on Kubernetes
type: application
version: 0.0.39
appVersion: "0.0.40"

dependencies:
  - name: nats
    version: "1.2.*"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
