import { extractWebAuthType } from "@contfu/svc-core";
import { Effect } from "effect";
import crypto from "node:crypto";
import type { BackendSource, CreateSourceInput } from "../../domain/types";
import { Crypto } from "../../effect/services/Crypto";
import { Database } from "../../effect/services/Database";
import { DatabaseError } from "../../effect/errors";
import { sourceTable, type Source } from "../../infra/db/schema";

/** Source type: Web (for extracting auth type) */
const SOURCE_TYPE_WEB = 2;

function mapToBackendSource(source: Source): BackendSource {
  const baseSource: BackendSource = {
    id: source.id,
    uid: source.uid,
    userId: source.userId,
    name: source.name,
    url: source.url,
    includeRef: source.includeRef,
    type: source.type,
    hasCredentials: source.credentials !== null,
    hasWebhookSecret: source.webhookSecret !== null,
    credentialsSource: source.credentialsSource,
    createdAt: source.createdAt,
    updatedAt: source.updatedAt,
  };

  // Add webAuthType for web sources
  if (source.type === SOURCE_TYPE_WEB) {
    return {
      ...baseSource,
      webAuthType: extractWebAuthType(source.credentials),
    };
  }

  return baseSource;
}

/**
 * Create a new source for a user.
 * The ID is auto-generated by the database.
 * Credentials and webhookSecret are encrypted before storage.
 *
 * @returns The created source without credentials
 */
export const createSource = (userId: number, input: CreateSourceInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;
    const cryptoService = yield* Crypto;

    // Encrypt credentials and webhookSecret
    const [encryptedCredentials, encryptedWebhookSecret] = yield* Effect.all([
      cryptoService.encryptCredentials(userId, input.credentials ?? null),
      cryptoService.encryptCredentials(userId, input.webhookSecret ?? null),
    ]);

    const [inserted] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(sourceTable)
          .values({
            userId,
            uid: crypto.randomUUID(),
            name: input.name,
            type: input.type,
            url: input.url ?? null,
            includeRef: input.includeRef ?? true,
            credentials: encryptedCredentials,
            webhookSecret: encryptedWebhookSecret,
            credentialsSource: input.credentialsSource ?? null,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return mapToBackendSource(inserted);
  }).pipe(Effect.withSpan("sources.create", { attributes: { userId } }));
