import type { BackendCollection } from "../../domain/types";
import { db } from "../../infra/db/db";
import { collectionTable } from "../../infra/db/schema";

export interface CreateCollectionInput {
  name: string;
}

/**
 * Create a new Collection for a user.
 * This is the target that consumers subscribe to.
 * The ID is auto-generated by the database.
 */
export async function createCollection(
  userId: number,
  input: CreateCollectionInput,
): Promise<BackendCollection> {
  const [inserted] = await db
    .insert(collectionTable)
    .values({
      userId,
      name: input.name,
    })
    .returning();

  return {
    id: inserted.id,
    userId: inserted.userId,
    name: inserted.name,
    influxCount: 0,
    connectionCount: 0,
    createdAt: inserted.createdAt,
    updatedAt: inserted.updatedAt,
  };
}
