import { Effect } from "effect";
import type { BackendCollection } from "../../domain/types";
import { Database } from "../../effect/services/Database";
import { DatabaseError } from "../../effect/errors";
import { collectionTable } from "../../infra/db/schema";
import { toCamelCase } from "@contfu/svc-core";

export interface CreateCollectionInput {
  displayName: string;
  name?: string;
  includeRef?: boolean;
}

const camelCasePattern = /^[a-z][a-zA-Z0-9]*$/;

/**
 * Create a new Collection for a user.
 * This is the target that consumers subscribe to.
 * The ID is auto-generated by the database.
 */
export const createCollection = (userId: number, input: CreateCollectionInput) =>
  Effect.gen(function* () {
    const { db } = yield* Database;

    const name = input.name ?? toCamelCase(input.displayName);

    if (!camelCasePattern.test(name)) {
      yield* Effect.fail(
        new DatabaseError({
          cause: new Error(
            `Collection name "${name}" must be a camelCase identifier (e.g. "blogPosts")`,
          ),
        }),
      );
    }

    const [inserted] = yield* Effect.tryPromise({
      try: () =>
        db
          .insert(collectionTable)
          .values({
            userId,
            displayName: input.displayName,
            name,
            includeRef: input.includeRef ?? true,
          })
          .returning(),
      catch: (e) => new DatabaseError({ cause: e }),
    });

    return {
      id: inserted.id,
      userId: inserted.userId,
      displayName: inserted.displayName,
      name: inserted.name,
      includeRef: inserted.includeRef,
      influxCount: 0,
      connectionCount: 0,
      createdAt: inserted.createdAt,
      updatedAt: inserted.updatedAt,
    } satisfies BackendCollection;
  }).pipe(Effect.withSpan("collections.create", { attributes: { userId } }));
