export {
  PropertyType,
  type CollectionSchema,
  type GeoPoint,
  type SchemaValue,
  type RefTargets,
  type TypeGenerationInput,
  type ComponentSchema,
  schemaType,
  schemaEnumValues,
  mergeSchemaValues,
  generateTypeScript,
  generateApplicationIntegrationTypes,
  generateConsumerTypes,
  isSystemSchemaKey,
} from "@contfu/core";
