export {
  PropertyType,
  PROPERTY_TYPE_MASK,
  PROPERTY_METADATA_MASK,
  propertyTypeBase,
  propertyTypeMetadata,
  hasPropertyType,
  type CollectionSchema,
  type GeoPoint,
  type SchemaValue,
  type RefTargets,
  type TypeGenerationInput,
  type ComponentSchema,
  schemaType,
  schemaEnumValues,
  mergeSchemaValues,
  generateTypeScript,
  generateApplicationIntegrationTypes,
  isSystemSchemaKey,
} from "@contfu/core";
